name: Go

on:
  push:
    branches:
      - main
      - release
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Build
      #run: ./build/build.sh
      run: ls

    #- name: Test
     # run: go test -v ./...
