name: Build-Release

on:
  workflow_dispatch:
  push:
    branches:
      - release

jobs:

  build-linux-arm64:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15
    - name: Build Linux-arm64
      run: |
        env GOOS=linux GOARCH=arm64
        go build -o bin/main-linux-arm64 main.go
      continue-on-error: true
    
    - name: Upload Artifacts
      uses: actions/upload-artifact@v2.2.2
      with:
        name: main-linux-arm64
        path: ./bin/main-linux-arm64
        
  build-linux-armv6:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Build Linux-armv6
      run: |
        env GOOS=linux GOARM=6 GOARCH=arm
        go build -o bin/main-linux-armv6 main.go
      continue-on-error: true
        
    - name: Upload Artifacts
      uses: actions/upload-artifact@v2.2.2
      with:
        name: main-linux-armv6
        path: ./bin/main-linux-armv6

  build-windows-386:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15
        
    - name: Build Windows-386
      run: |
        env GOOS=linux GOARCH=386
        go build -o bin/main-windows-386 main.go
      continue-on-error: true
      
    - name: Upload Artifacts
      uses: actions/upload-artifact@v2.2.2
      with:
         path: ./bin

  build-windows-amd64:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15
        
    - name: Build Windows-amd64
      run: |
        env GOOS=windows GOARCH=amd64
        go build -o bin/main-windows-amd64 main.go
      continue-on-error: true
        
    - name: Upload Artifacts
      uses: actions/upload-artifact@v2.2.2
      with:
         path: ./bin



