name: Build-Release

on:
  workflow_dispatch:
  push:
    branches:
      - release

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Build Linux-arm64
      run: |
        env GOOS=linux GOARCH=arm64
        go build -o bin/main-linux-arm64 main.go
      
    - name: Build Linux-armv6
      run: |
        env GOOS=linux GOARM=6 GOARCH=arm
        go build -o bin/main-linux-armv6 main.go
        
    - name: Build Windows-386
      run: |
        env GOOS=linux GOARCH=386
        go build -o bin/main-windows-386
    - name: Upload Artifacts
      uses: actions/upload-artifact@v2.2.2
      with:
         name: main-linux-arm64
         path: ./
